name: rdkit-osmordred CIBuildWheel
on:
  workflow_dispatch:
jobs:
  build_wheels:
    name: Build wheels on mac
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Build
        env:
          CIBW_PLATFORM: macos
          CIBW_BUILD: cp311-macosx_arm64
          CIBW_ARCHS: all
        shell: bash
        run: |
          NO_CONDA=1 build_patched_rdkit-pypi/build_rdkit-pypi.sh

      - name: Save Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true